In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv(r"C:\Users\vinit\Downloads\bostonhousing\boston.csv")
df

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296.0,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242.0,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242.0,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222.0,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222.0,18.7,396.90,5.33,36.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0,0.573,6.593,69.1,2.4786,1,273.0,21.0,391.99,9.67,22.4
502,0.04527,0.0,11.93,0,0.573,6.120,76.7,2.2875,1,273.0,21.0,396.90,9.08,20.6
503,0.06076,0.0,11.93,0,0.573,6.976,91.0,2.1675,1,273.0,21.0,396.90,5.64,23.9
504,0.10959,0.0,11.93,0,0.573,6.794,89.3,2.3889,1,273.0,21.0,393.45,6.48,22.0
505,0.04741,0.0,11.93,0,0.573,6.030,80.8,2.5050,1,273.0,21.0,396.90,7.88,11.9

In [3]:
x = df.iloc[:,:13]
x

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296.0,15.3,396.90,4.98
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242.0,17.8,396.90,9.14
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242.0,17.8,392.83,4.03
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222.0,18.7,394.63,2.94
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222.0,18.7,396.90,5.33
...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0,0.573,6.593,69.1,2.4786,1,273.0,21.0,391.99,9.67
502,0.04527,0.0,11.93,0,0.573,6.120,76.7,2.2875,1,273.0,21.0,396.90,9.08
503,0.06076,0.0,11.93,0,0.573,6.976,91.0,2.1675,1,273.0,21.0,396.90,5.64
504,0.10959,0.0,11.93,0,0.573,6.794,89.3,2.3889,1,273.0,21.0,393.45,6.48
505,0.04741,0.0,11.93,0,0.573,6.030,80.8,2.5050,1,273.0,21.0,396.90,7.88

In [4]:
y = df.iloc[:,13:]
y

     MEDV
0    24.0
1    21.6
2    34.7
3    33.4
4    36.2
..    ...
501  22.4
502  20.6
503  23.9
504  22.0
505  11.9

[506 rows x 1 columns]

In [5]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2)

ss = StandardScaler()
ss.fit(x_train)
x_train = ss.transform(x_train)
x_test = ss.transform(x_test)

In [6]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

model = Sequential()
model.add(Dense(128, activation = 'relu', input_shape = (13,)))
model.add(Dense(64, activation = 'relu'))
model.add(Dense(1, activation = 'linear'))

In [7]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 128)               1792

 dense_1 (Dense)             (None, 64)                8256

 dense_2 (Dense)             (None, 1)                 65

=================================================================
Total params: 10,113
Trainable params: 10,113
Non-trainable params: 0
_________________________________________________________________

In [8]:
model.compile(optimizer = 'adam', loss = 'mse', metrics = 'mae')
model.fit(x_train, y_train, epochs = 50, validation_split = 0.1)

Epoch 1/50
12/12 [==============================] - 1s 23ms/step - loss: 576.7624 - mae: 22.0228 - val_loss: 453.5956 - val_mae: 20.2156
Epoch 2/50
12/12 [==============================] - 0s 7ms/step - loss: 503.9895 - mae: 20.2319 - val_loss: 373.4923 - val_mae: 17.9937
Epoch 3/50
12/12 [==============================] - 0s 6ms/step - loss: 415.5294 - mae: 17.9265 - val_loss: 275.8342 - val_mae: 15.0002
Epoch 4/50
12/12 [==============================] - 0s 7ms/step - loss: 305.3744 - mae: 15.0286 - val_loss: 167.7211 - val_mae: 11.4349
Epoch 5/50
12/12 [==============================] - 0s 10ms/step - loss: 188.7362 - mae: 11.3555 - val_loss: 79.2590 - val_mae: 7.7300
Epoch 6/50
12/12 [==============================] - 0s 6ms/step - loss: 106.2956 - mae: 8.1225 - val_loss: 49.4595 - val_mae: 5.8792
Epoch 7/50
12/12 [==============================] - 0s 7ms/step - loss: 68.5220 - mae: 6.2745 - val_loss: 41.4082 - val_mae: 5.1078
Epoch 8/50
12/12 [==============================] - 0s 6ms/step - loss: 47.9976 - mae: 5.1997 - val_loss: 31.9788 - val_mae: 4.4894
Epoch 9/50
12/12 [==============================] - 0s 6ms/step - loss: 35.8934 - mae: 4.4063 - val_loss: 26.4851 - val_mae: 4.0577
Epoch 10/50
12/12 [==============================] - 0s 7ms/step - loss: 28.8428 - mae: 3.9250 - val_loss: 23.0346 - val_mae: 3.7458
Epoch 11/50
12/12 [==============================] - 0s 7ms/step - loss: 25.3512 - mae: 3.6640 - val_loss: 19.5915 - val_mae: 3.4269
Epoch 12/50
12/12 [==============================] - 0s 6ms/step - loss: 23.0404 - mae: 3.4916 - val_loss: 16.4844 - val_mae: 3.1428
Epoch 13/50
12/12 [==============================] - 0s 6ms/step - loss: 21.4120 - mae: 3.3470 - val_loss: 14.4056 - val_mae: 2.9312
Epoch 14/50
12/12 [==============================] - 0s 7ms/step - loss: 19.9257 - mae: 3.2183 - val_loss: 13.1777 - val_mae: 2.7825
Epoch 15/50
12/12 [==============================] - 0s 6ms/step - loss: 18.9571 - mae: 3.1498 - val_loss: 12.5767 - val_mae: 2.6606
Epoch 16/50
12/12 [==============================] - 0s 7ms/step - loss: 18.0094 - mae: 3.0652 - val_loss: 11.6892 - val_mae: 2.5311
Epoch 17/50
12/12 [==============================] - 0s 6ms/step - loss: 17.2171 - mae: 2.9621 - val_loss: 11.0038 - val_mae: 2.4850
Epoch 18/50
12/12 [==============================] - 0s 6ms/step - loss: 16.5105 - mae: 2.8742 - val_loss: 10.8900 - val_mae: 2.4649
Epoch 19/50
12/12 [==============================] - 0s 6ms/step - loss: 16.0450 - mae: 2.8600 - val_loss: 10.6510 - val_mae: 2.4541
Epoch 20/50
12/12 [==============================] - 0s 7ms/step - loss: 15.3772 - mae: 2.7955 - val_loss: 10.5871 - val_mae: 2.4543
Epoch 21/50
12/12 [==============================] - 0s 7ms/step - loss: 14.9048 - mae: 2.7193 - val_loss: 9.9449 - val_mae: 2.4164
Epoch 22/50
12/12 [==============================] - 0s 7ms/step - loss: 14.6142 - mae: 2.7009 - val_loss: 9.8828 - val_mae: 2.4455
Epoch 23/50
12/12 [==============================] - 0s 6ms/step - loss: 14.0570 - mae: 2.6427 - val_loss: 9.6102 - val_mae: 2.4408
Epoch 24/50
12/12 [==============================] - 0s 6ms/step - loss: 13.7895 - mae: 2.5927 - val_loss: 9.3385 - val_mae: 2.4184
Epoch 25/50
12/12 [==============================] - 0s 7ms/step - loss: 13.4033 - mae: 2.5593 - val_loss: 9.0175 - val_mae: 2.4065
Epoch 26/50
12/12 [==============================] - 0s 7ms/step - loss: 13.2076 - mae: 2.5476 - val_loss: 8.9491 - val_mae: 2.4147
Epoch 27/50
12/12 [==============================] - 0s 7ms/step - loss: 12.8424 - mae: 2.5049 - val_loss: 8.7131 - val_mae: 2.3829
Epoch 28/50
12/12 [==============================] - 0s 6ms/step - loss: 12.6286 - mae: 2.4773 - val_loss: 8.9080 - val_mae: 2.3990
Epoch 29/50
12/12 [==============================] - 0s 7ms/step - loss: 12.4827 - mae: 2.4715 - val_loss: 8.8775 - val_mae: 2.3944
Epoch 30/50
12/12 [==============================] - 0s 7ms/step - loss: 12.2136 - mae: 2.4182 - val_loss: 8.4637 - val_mae: 2.3654
Epoch 31/50
12/12 [==============================] - 0s 7ms/step - loss: 11.8423 - mae: 2.4056 - val_loss: 8.7734 - val_mae: 2.3649
Epoch 32/50
12/12 [==============================] - 0s 7ms/step - loss: 11.7019 - mae: 2.3999 - val_loss: 8.6272 - val_mae: 2.3697
Epoch 33/50
12/12 [==============================] - 0s 6ms/step - loss: 11.4994 - mae: 2.3654 - val_loss: 8.7865 - val_mae: 2.3678
Epoch 34/50
12/12 [==============================] - 0s 7ms/step - loss: 11.2643 - mae: 2.3309 - val_loss: 8.6156 - val_mae: 2.3601
Epoch 35/50
12/12 [==============================] - 0s 6ms/step - loss: 11.0860 - mae: 2.3075 - val_loss: 8.4748 - val_mae: 2.3385
Epoch 36/50
12/12 [==============================] - 0s 6ms/step - loss: 10.9548 - mae: 2.2941 - val_loss: 8.3677 - val_mae: 2.3268
Epoch 37/50
12/12 [==============================] - 0s 7ms/step - loss: 10.8178 - mae: 2.2916 - val_loss: 8.5540 - val_mae: 2.3382
Epoch 38/50
12/12 [==============================] - 0s 6ms/step - loss: 10.7115 - mae: 2.2707 - val_loss: 8.2783 - val_mae: 2.3201
Epoch 39/50
12/12 [==============================] - 0s 6ms/step - loss: 10.5073 - mae: 2.2495 - val_loss: 8.4183 - val_mae: 2.3073
Epoch 40/50
12/12 [==============================] - 0s 7ms/step - loss: 10.4043 - mae: 2.2401 - val_loss: 8.3147 - val_mae: 2.2873
Epoch 41/50
12/12 [==============================] - 0s 7ms/step - loss: 10.2940 - mae: 2.2249 - val_loss: 8.4056 - val_mae: 2.3167
Epoch 42/50
12/12 [==============================] - 0s 13ms/step - loss: 10.1400 - mae: 2.1968 - val_loss: 8.2888 - val_mae: 2.2805
Epoch 43/50
12/12 [==============================] - 0s 9ms/step - loss: 10.0810 - mae: 2.1929 - val_loss: 8.2670 - val_mae: 2.2929
Epoch 44/50
12/12 [==============================] - 0s 8ms/step - loss: 9.9352 - mae: 2.1661 - val_loss: 8.1673 - val_mae: 2.2957
Epoch 45/50
12/12 [==============================] - 0s 7ms/step - loss: 9.8319 - mae: 2.1736 - val_loss: 8.2697 - val_mae: 2.2478
Epoch 46/50
12/12 [==============================] - 0s 8ms/step - loss: 9.8582 - mae: 2.1860 - val_loss: 8.1950 - val_mae: 2.2423
Epoch 47/50
12/12 [==============================] - 0s 8ms/step - loss: 9.6295 - mae: 2.1518 - val_loss: 8.4065 - val_mae: 2.2933
Epoch 48/50
12/12 [==============================] - 0s 7ms/step - loss: 9.4861 - mae: 2.1318 - val_loss: 8.4262 - val_mae: 2.2674
Epoch 49/50
12/12 [==============================] - 0s 9ms/step - loss: 9.4307 - mae: 2.1211 - val_loss: 8.4150 - val_mae: 2.2527
Epoch 50/50
12/12 [==============================] - 0s 8ms/step - loss: 9.4734 - mae: 2.1275 - val_loss: 8.0890 - val_mae: 2.2078

In [9]:
output = model.evaluate(x_test, y_test)

4/4 [==============================] - 0s 6ms/step - loss: 13.7060 - mae: 2.6040

In [12]:
y_pred = model.predict(x_test)

4/4 [==============================] - 0s 7ms/step

In [16]:
print(y_pred[0])

[22.164984]

In [18]:
print(y_test)

     MEDV
313  21.6
310  16.1
329  22.6
491  13.6
177  24.6
..    ...
372  50.0
158  24.3
50   19.7
214  23.7
157  41.3

[102 rows x 1 columns]